config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  resources :users
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :new_tweet
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  def new_tweet
    @new_tweet = Tweet.new
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_tweets = Tweet.all
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def create
    new_tweet = current_user.tweets.new(tweet_params)
    new_tweet.save
    redirect_to tweet_path(new_tweet.id)
  end
  def destroy
  end
  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @all_users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>About!</h1>

app/views/homes/top.html.erb
<h1>topページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
      <% if user_signed_in? %>
        <li><%= link_to 'users', users_path %></li>
        <li><%= link_to 'tweets', tweets_path %></li>
        <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'log in', new_user_session_path %></li>
        <li><%= link_to 'sign up', new_user_registration_path %></li>
      <% end %>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/_new_tweet_form.html.erb
<h2>New Tweet</h2>
<%= form_for @new_tweet do |t| %>
<%= t.text_field :content %>
<% end %>

app/views/tweets/index.html.erb
<h1>tweet Index</h1>
<table>
  <thead>
    <tr>
      <th>content</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @all_tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.content %></td>
      <td><%= link_to "Show", tweet_path(tweet.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= render 'tweets/new_tweet_form' %>

app/views/tweets/show.html.erb
<h1>Tweet Show</h1>
<h2>tweet</h2>
<%= @tweet.content %>
<h2>tweet user</h2>
<%= @tweet.user.name %>
<%= render 'tweets/new_tweet_form' %>

app/views/users/index.html.erb
<h1>User Index</h1>
<table>
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>tweet count</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @all_users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.tweets.count %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= render 'tweets/new_tweet_form' %>

app/views/users/show.html.erb
<h1>User Show</h1>
<h2>user name</h2>
<%= @user.name %>
<h2>user email</h2>
<%= @user.email %>
<h2>user tweets</h2>
<table>
  <thead>
    <tr>
      <th>content</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.content %></td>
      <td><%= link_to "Show", tweet_path(tweet.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= render 'tweets/new_tweet_form' %>